### ISSUE TITLE
技术文档有奖翻译！

### ISSUE THREAD

**Issue by dc0921** [HP-Enterprise/Training#1]
# 有奖翻译
### 群策群力，团结就是力量！:sparkles:
1. 《Gradle教程》 奖励500rmb ：第4（60rmb）,6（200rmb）,7章（240rmb）
2. 《GitHub训练营》奖励100rmb： 前2章 Set Up Git & Create A Repo
3. 《GitHub Hello-World》奖励200rmb
4. 《精通 Issues》 奖励150rmb
5. 《精通 Markdown》奖励50rmb

翻译内容详细请参考链接：https://github.com/HP-Enterprise/Training

**Comment by mqwangincar** [comment]
各位，

首先，一份标准的、易懂的文档有助于我们加快效率。

其次，一次翻译，对自己而言也是一次成长，可以更好的理解相关内容，同时锻炼文档写作水平

最后，文档将署你的名字，所有新加入英卡的工程师将阅读你的文档

最后，我们期望十月完成此认为，且大家可预订自己翻译那一项内容，避免多人做同一件事情。 

谢谢！

王明青| InCar
