### ISSUE TITLE
大师面对面 | TypeScript之父 - Anders Hejlsberg

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Training#11]
# 大师面对面 | TypeScript之父
## 活动内容

2015年10月24日，Anders Hejlsberg 将来到北京，与广大TypeScript开发者和编程爱好者见面，分享最新的技术动态并与您进行巅峰对话。您将有机会与Anders零距离沟通，一睹大师风采，并享用一场关于TypeScript编程之美的饕餮盛宴！

在这场巅峰对话上，Anders将向您介绍关于TypeScript开源项目的最新进展以及未来的发展路线，分享TypeScript在项目实施中的最佳实践，同时，您还可以与Anders交流开发中的点滴感悟，提出问题，或对TypeScript项目给予反馈和改进建议。我们还邀请了来自国内主要社区的开发者和TypeScript重度用户，与您交流他们在TypeScript实践过程中积累的经验，相信您将不虚此行！

![Anders Hejlsberg](http://cdn.huodongxing.com/file/20150306/112C50C0C3D11FB14E2261A0F2502E992A/30762110460771768.jpeg)
**Anders Hejlsberg安德斯·海尔斯伯格**

全球知名的软件开发大师，Delphi 和 C#之父，Turbo Pascal 编译器的主要作者，.NET 概念发起人之一，同时也是TypeScript开源项目的重要领导人。他于1996年加入微软，目前是 C# 语言的首席架构师和 TypeScript 的核心开发者，获微软卓越工程师 Distinguished Engineer 和微软技术院士 Technical Fellow 称号。
### 时间及城市：

10月24日14:00 – 16:00
北京市朝阳区望京街8号利星行广场C座微软大厦3层
### 报名网站:

http://www.huodongxing.com/event/6303905634100

---

有兴趣报名的 请在此贴后跟贴 并自己在报名网站报名
公司报销 往返交通和住宿

你也可以在 GitHub里关注 Anders Hejlsberg , 查看他每天都在做什么
https://github.com/ahejlsberg

**Comment by TeemolSparrow** [comment]
![img_0201](https://cloud.githubusercontent.com/assets/13936823/10475835/87840160-727a-11e5-9b1c-86883141c2db.PNG)

**Comment by septwong** [comment]
![199506023915843491](https://cloud.githubusercontent.com/assets/9412495/10475899/187a852c-727b-11e5-88e3-9d7be8629976.jpg)

**Comment by jiangli0509** [comment]
![baoming](https://cloud.githubusercontent.com/assets/5874912/10475912/4e8d979e-727b-11e5-90f4-797fceffd364.jpg)

**Comment by any0921** [comment]
![Uploading IMG_5613.PNG…]()

**Comment by any0921** [comment]
![image of 1](http://img3.douban.com/view/photo/photo/Z4fmJ2CQCm2IF3Zikw63sQ/135989898/x2274717080.jpg)

**Comment by AceBear** [comment]
![ms](https://cloud.githubusercontent.com/assets/5030312/10841160/e3be82f8-7f21-11e5-9ed9-3a2756126f84.jpg)

[Share-BeiJing.pptx](http://ic-media.oss-cn-hangzhou.aliyuncs.com/2015%2F10%2FShare-BeiJing.pptx)
