### ISSUE TITLE
 GitHub训练营 前2章-￥100

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Training#5]
- [_《GitHub训练营》_ 前2章[English] `Set Up Git` & `Create A Repo`](https://help.github.com/categories/bootcamp)
- 奖励 **RMB100元**  :moneybag: :100: 
- 参见 #1 技术文档有奖翻译

**Comment by dc0921** [comment]
nice work！

https://github.com/HP-Enterprise/Training/blob/master/GitHub/Set%20up%20Git.md
https://github.com/HP-Enterprise/Training/blob/master/GitHub/Creat%20a%20Repo.md
