### ISSUE TITLE
GitHub Hello-World 全文- ￥200

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Training#6]
- [_《GitHub Hello-World》_[English]](https://guides.github.com/activities/hello-world)
- 奖励 **RMB200元**  :moneybag: :100:  :moneybag: :100: 
- 参见 #1 技术文档有奖翻译

**Comment by dc0921** [comment]
nice work!
https://github.com/HP-Enterprise/Training/blob/master/GitHub/GitHub-HelloWorld.md
