### ISSUE TITLE
精通Issues全文 - ￥150

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Training#7]
- [_《精通 Issues》_[English]](https://guides.github.com/features/issues)
- 奖励 **RMB150元**  :moneybag: :100:  :dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten:
- 参见 #1 技术文档有奖翻译

**Comment by dc0921** [comment]
nice work!
https://github.com/HP-Enterprise/Training/blob/master/GitHub/issues.md
