### ISSUE TITLE
精通Markdown全文 - ￥50 

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Training#8]
- [_《精通 Markdown》_[English]](https://guides.github.com/features/mastering-markdown)
- 奖励 **RMB50元**  :dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten::dollar::keycap_ten:
- 参见 #1 技术文档有奖翻译

**Comment by dc0921** [comment]
nice work~！
https://github.com/HP-Enterprise/Training/blob/master/GitHub/精通Markdown.md
